### PR TITLE
Attempt authing two times before failing

### LINKED ISSUE #11: Enter a valid email or mobile number error after running smoothly for a while.
```
rake aborted!
KindleHighlights::Client::AuthenticationError: Unable to sign in, received error: 'Enter a valid email or mobile number'
/Users/cggaurav/.rvm/gems/ruby-2.1.2/gems/kindle-highlights-1.0.1/lib/kindle_highlights/client.rb:55:in `conditionally_sign_in_to_amazon'
/Users/cggaurav/.rvm/gems/ruby-2.1.2/gems/kindle-highlights-1.0.1/lib/kindle_highlights/client.rb:63:in `load_books_from_kindle_account'
/Users/cggaurav/.rvm/gems/ruby-2.1.2/gems/kindle-highlights-1.0.1/lib/kindle_highlights/client.rb:16:in `books'
/Users/cggaurav/Projects/apps/play/highlights/Rakefile:30:in `update'
/Users/cggaurav/Projects/apps/play/highlights/Rakefile:56:in `block in <top (required)>'
/Users/cggaurav/.rvm/gems/ruby-2.1.2/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => default => download
(See full trace by running task with --trace)
```

### PR DESCRIPTION
**Pull request by sirupsen**
This should fix https://github.com/speric/kindle-highlights/issues/11

@speric

### CODE REVIEW

**Comment by sirupsen** [comment]
Bump @speric ^

File: lib/kindle_highlights/client.rb [hunk 1]
```diff
@@ -40,6 +42,8 @@ def highlights_for(asin)
     attr_accessor :email_address, :password, :mechanize_options
 
     def conditionally_sign_in_to_amazon
+      retries ||= 0
```
Comment (speric) [inline lib/kindle_highlights/client.rb:45]: What's the motivation to use `||=` instead of just initializing it as `retries = 0`?

Comment (sirupsen) [reply lib/kindle_highlights/client.rb:45]: Otherwise it'll cause an infinite loop when the `retry` takes effect (resetting it back to 0). `||=` preserves the value from the past retry.

Comment (speric) [reply lib/kindle_highlights/client.rb:45]: Ah, I didn't see it in context of the whole method.

Nice change!

**Comment by speric** [comment]
👍 Thanks!
